set(HepMC3Version 3.2.7)
set(HepMC3SHA256 587faa6556cc54ccd89ad35421461b4761d7809bc17a2e72f5034daea142232b)

include(FetchContent)

set(HEPMC3_ENABLE_ROOTIO OFF CACHE BOOL "" FORCE)
set(HEPMC3_ENABLE_PYTHON OFF CACHE BOOL "" FORCE)
set(HEPMC3_BUILD_EXAMPLES OFF CACHE BOOL "" FORCE)
set(HEPMC3_BUILD_SHARED_LIBS ON CACHE BOOL "" FORCE)
set(HEPMC3_INSTALL_INTERFACES ON CACHE BOOL "" FORCE)

FetchContent_Declare(HepMC3
    URL https://gitlab.cern.ch/hepmc/HepMC3/-/archive/${HepMC3Version}/HepMC3-${HepMC3Version}.tar.gz
    URL_HASH SHA256=${HepMC3SHA256}
    DOWNLOAD_DIR ${PROJECT_BINARY_DIR}/ThirdParty/tmp
    SOURCE_DIR ${PROJECT_BINARY_DIR}/ThirdParty/HepMC3
    BINARY_DIR ${PROJECT_BINARY_DIR}/ThirdParty/HepMC3-build
)
FetchContent_MakeAvailable(HepMC3)

set(BUILT_EXTERNAL_DEPENDENCIES ON CACHE BOOL "" FORCE)
