///
/// @file  TestAmplLbLcstar32LepNu.cc
/// @brief Tests for AmplLbLcstar32LepNu
///

//**** This file is a part of the HAMMER library
//**** Copyright (C) 2016 - 2026 The HAMMER Collaboration
//**** HAMMER is licensed under version 3 of the GPL; see COPYING for details
//**** Please note the MCnet academic guidelines; see GUIDELINES for details

#include "Hammer/Amplitudes/AmplLbLcstar32LepNu.hh"
#include "Hammer/Math/Constants.hh"
#include "Hammer/Math/FourMomentum.hh"
#include "Hammer/Math/Utils.hh"
#include "Hammer/Math/MultiDim/VectorContainer.hh"
#include "Hammer/Particle.hh"
#include "Hammer/Tools/Pdg.hh"
#include "gtest/gtest.h"
// May need other stuff here

using namespace std;
using namespace complex_literals;

namespace Hammer {

    namespace MD = MultiDimensional;

    TEST(AmplLbLcstar32LepNuTest, eval) {

        // Momentum decs
        FourMomentum pLbmes{5620., 0., 0., 0.};
        FourMomentum pLcmes{3067.17304270463, 0, 0, -1586.48210638947};
        FourMomentum kNuTau{103.858273281499, -16.4797557212763, -28.5437742055744, -98.4896519157352};
        FourMomentum pTau{2448.96868401388, 16.4797557212763, 28.5437742055744, 1684.97175830520};

        // Create FF
        Tensor FFvec{"FFvec",
                     MD::makeVector({16}, {FF_LBLCSTAR32},
                                    {1.1, 0.8, 0.9, 0.4, 0.3, 0.1, 1.1, 0.5, 0.2, 0.3, 1.2, 0.3, 0.2, 0.1, 0.5, 0.3})};

        // Evaluate
        AmplLbLcstar32LepNu ampl;
        ampl.eval(Particle(pLbmes, -5122), {Particle(pLcmes, -4124), Particle(kNuTau, 16), Particle(pTau, -15)}, {});
        auto t = ampl.getTensor();
        t.dot(FFvec, {FF_LBLCSTAR32});

        // Compare to direct evaluation
        Tensor amplEval{"amplEval", MD::makeVector({2, 4, 2, 2, 11},
                                                   {SPIN_LB, SPIN_LCSTAR32, SPIN_NUTAU, SPIN_TAUP, WILSON_BCTAUNU},
                                                   {0,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    -853893.662017417,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    614432.859712791,
                                                    0,
                                                    -853893.662017417,
                                                    0,
                                                    -1.93293862309128e6,
                                                    0,
                                                    -1.22122707388486e7,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    8.78753499110119e6,
                                                    0,
                                                    -1.22122707388486e7,
                                                    0,
                                                    -2.18201196670338e7,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    -54429.6284327724,
                                                    0,
                                                    75642.3000658404,
                                                    0,
                                                    -200066.703467589,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    -614432.859712791,
                                                    0,
                                                    853893.662017417,
                                                    0,
                                                    -2.86132671696222e6,
                                                    -4.48126821991107e6,
                                                    6.77956302901495e6,
                                                    0,
                                                    4.49433961155662e6,
                                                    0,
                                                    -713592.637531369,
                                                    0,
                                                    -4.48126821991107e6,
                                                    0,
                                                    -4.59964456544114e7,
                                                    0,
                                                    -815753.626568116,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    -2.6906151971532e6,
                                                    0,
                                                    -815753.626568116,
                                                    0,
                                                    6.47232031823982e6,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    -2.6906151971532e6,
                                                    0,
                                                    -815753.626568116,
                                                    0,
                                                    -102129.437785001,
                                                    0,
                                                    0,
                                                    -6.77956302901495e6,
                                                    0,
                                                    -4.49433961155662e6,
                                                    0,
                                                    713592.637531369,
                                                    0,
                                                    4.48126821991107e6,
                                                    0,
                                                    -725797.071809777,
                                                    -187386.15825991,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    -16722.7748522297,
                                                    0,
                                                    -187386.15825991,
                                                    0,
                                                    9.64551193380915e6,
                                                    0,
                                                    16599.6313613486,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    1481.38955653713,
                                                    0,
                                                    16599.6313613486,
                                                    0,
                                                    -674423.428969076,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    -239166.846042327,
                                                    0,
                                                    -2.67997128820014e6,
                                                    0,
                                                    8.87596813100262e6,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    16722.7748522297,
                                                    0,
                                                    187386.15825991,
                                                    0,
                                                    -786278.98836242,
                                                    -16722.7748522297,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    -187386.15825991,
                                                    0,
                                                    -16722.7748522297,
                                                    0,
                                                    786278.98836242,
                                                    0,
                                                    -239166.846042327,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    -2.67997128820014e6,
                                                    0,
                                                    -239166.846042327,
                                                    0,
                                                    8.87596813100262e6,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    16599.6313613486,
                                                    0,
                                                    1481.38955653713,
                                                    0,
                                                    -674423.428969076,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    187386.15825991,
                                                    0,
                                                    16722.7748522297,
                                                    0,
                                                    -9.64551193380915e6,
                                                    -713592.637531369,
                                                    4.49433961155662e6,
                                                    0,
                                                    6.77956302901495e6,
                                                    0,
                                                    -4.48126821991107e6,
                                                    0,
                                                    -713592.637531369,
                                                    0,
                                                    725797.071809777,
                                                    0,
                                                    -2.6906151971532e6,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    -815753.626568116,
                                                    0,
                                                    -2.6906151971532e6,
                                                    0,
                                                    -102129.437785001,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    -815753.626568116,
                                                    0,
                                                    -2.6906151971532e6,
                                                    0,
                                                    6.47232031823982e6,
                                                    0,
                                                    0,
                                                    -4.49433961155662e6,
                                                    0,
                                                    -6.77956302901495e6,
                                                    0,
                                                    4.48126821991107e6,
                                                    0,
                                                    713592.637531369,
                                                    0,
                                                    4.59964456544114e7,
                                                    -614432.859712791,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    853893.662017417,
                                                    0,
                                                    -614432.859712791,
                                                    0,
                                                    -2.86132671696222e6,
                                                    0,
                                                    54429.6284327724,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    -75642.3000658404,
                                                    0,
                                                    54429.6284327724,
                                                    0,
                                                    200066.703467589,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    1.22122707388486e7,
                                                    0,
                                                    -8.78753499110119e6,
                                                    0,
                                                    2.18201196670338e7,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    -853893.662017417,
                                                    0,
                                                    614432.859712791,
                                                    0,
                                                    -1.93293862309128e6,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    0,
                                                    0})};
        amplEval *= GFermi;


        // Check TEs. Care that nuTau spin is double-copied; second entry is ref qu.no.
        for (IndexType idx1 = 0; idx1 < 2; ++idx1) {
            for (IndexType idx2 = 0; idx2 < 4; ++idx2) {
                for (IndexType idx3 = 0; idx3 < 2; ++idx3) {
                    for (IndexType idx4 = 0; idx4 < 2; ++idx4) {
                        for (IndexType idx5 = 0; idx5 < 11; ++idx5) {
                            double comRe = compareVals(t.element({idx5, idx1, idx2, idx3, idx3, idx4}).real(),
                                                       amplEval.element({idx1, idx2, idx3, idx4, idx5}).real());
                            double comIm = compareVals(t.element({idx5, idx1, idx2, idx3, idx3, idx4}).imag(),
                                                       amplEval.element({idx1, idx2, idx3, idx4, idx5}).imag());
                            EXPECT_NEAR(comRe, 1., 1e-4);
                            EXPECT_NEAR(comIm, 1., 1e-4);
                        }
                    }
                }
            }
        }
    }


} // namespace Hammer
